#!/usr/bin/env python3
"""Generate projects/registry.yaml from every projects/<slug>/project.yaml.

The registry is a small, always-loaded index (one entry per project) so the agent can
enumerate projects and route to the right folder without reading the whole brain.
NEVER hand-edit registry.yaml — run this script.

Usage:
    python scripts/build_registry.py            # write registry.yaml
    python scripts/build_registry.py --check     # exit 1 if registry is stale (for CI/hooks)
"""
from __future__ import annotations
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
PROJECTS = ROOT / "projects"
REGISTRY = PROJECTS / "registry.yaml"


def load_manifests() -> list[dict]:
    entries = []
    for manifest in sorted(PROJECTS.glob("*/project.yaml")):
        if manifest.parent.name.startswith("_"):
            continue  # skip _template
        data = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
        entries.append({
            "id": data.get("id", manifest.parent.name),
            "name": data.get("name", ""),
            "status": data.get("status", "active"),
            "summary": data.get("summary", ""),
            "tags": data.get("tags", []),
            "repo": (data.get("github") or {}).get("repo", ""),
            "production_host": (data.get("production") or {}).get("host", ""),
            "connectors": data.get("connectors", []),
            "path": f"projects/{manifest.parent.name}/",
        })
    return entries


def render(entries: list[dict]) -> str:
    header = (
        "# GENERATED by scripts/build_registry.py — do not edit by hand.\n"
        "# Source of truth = each projects/<slug>/project.yaml manifest.\n\n"
    )
    body = yaml.safe_dump({"projects": entries}, allow_unicode=True, sort_keys=False)
    return header + body


def main() -> int:
    entries = load_manifests()
    out = render(entries)
    if "--check" in sys.argv:
        current = REGISTRY.read_text(encoding="utf-8") if REGISTRY.exists() else ""
        if current.strip() != out.strip():
            print("registry.yaml is stale — run: python scripts/build_registry.py")
            return 1
        print(f"registry.yaml up to date ({len(entries)} projects)")
        return 0
    REGISTRY.write_text(out, encoding="utf-8")
    print(f"wrote {REGISTRY} ({len(entries)} projects)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
