#!/usr/bin/env python3
"""Generate section-index.md — a greppable map of every doc → its H2/H3 sections.

Why: the brain's retrieval is "INDEX.md routing + frontmatter tags + grep" (see CLAUDE.md).
Big docs were split into topic files, but the agent still had to open a file to see its
sections. This index lets the agent grep one small file for a keyword and get back the exact
`path#anchor` to load — pointing at a section, not a whole file. It is the cheap, file-based
precursor to a future vector/RAG layer (same frontmatter hooks).

NEVER hand-edit section-index.md — run this script.

Usage:
    python scripts/build_section_index.py            # write section-index.md
    python scripts/build_section_index.py --check     # exit 1 if stale (for CI/hooks)
"""
from __future__ import annotations
import re
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "section-index.md"

# Skip generated/landing files and non-knowledge trees.
SKIP_NAMES = {"README.md", "CLAUDE.md", "INDEX.md", "section-index.md"}
SKIP_PARTS = {".git", "archive", "secrets-templates", "schema"}
HEADING_RE = re.compile(r"^(#{2,3})\s+(.*?)\s*#*$")  # H2 and H3 only


def anchor(text: str) -> str:
    """GitHub-flavored heading anchor (unicode-aware; keeps Cyrillic)."""
    s = text.strip().lower().replace("`", "")
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)  # drop punctuation
    s = re.sub(r"\s+", "-", s.strip())
    return s


def frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    try:
        return yaml.safe_load(text.split("---", 2)[1]) or {}
    except Exception:
        return {}


def doc_label(rel: str, fm: dict, is_skill: bool) -> str:
    if is_skill:
        name = fm.get("name", Path(rel).parent.name)
        return f"[skill] {name}"
    typ = fm.get("type", "?")
    tags = ", ".join(fm.get("tags", []) or [])
    return f"[{typ}]" + (f" {tags}" if tags else "")


def collect() -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Return [(rel_path, label, [(heading, anchor), ...]), ...] sorted by path."""
    entries = []
    for md in ROOT.rglob("*.md"):
        rel_parts = md.relative_to(ROOT).parts
        if any(p in SKIP_PARTS for p in rel_parts) or md.name in SKIP_NAMES:
            continue
        if any(p.startswith("_") for p in rel_parts):
            continue  # skip _template skeletons (parallel to build_registry.py)
        is_skill = "skills" in rel_parts
        if is_skill and md.name != "SKILL.md":
            continue  # only the skill's entry doc, not bundled references
        text = md.read_text(encoding="utf-8", errors="ignore")
        headings = []
        for line in text.split("\n"):
            m = HEADING_RE.match(line)
            if m:
                h = m.group(2).strip()
                if h:
                    headings.append((h, anchor(h)))
        if not headings:
            continue
        rel = md.relative_to(ROOT).as_posix()
        entries.append((rel, doc_label(rel, frontmatter(text), is_skill), headings))
    return sorted(entries, key=lambda e: e[0])


def render(entries) -> str:
    head = (
        "---\n"
        "id: section-index\n"
        "type: schema\n"
        "tags: [routing, index, generated, sections]\n"
        f"updated: {date.today().isoformat()}\n"
        "secret_refs: []\n"
        "---\n\n"
        "# Section index — GENERATED by scripts/build_section_index.py (do not hand-edit)\n\n"
        "Greppable map of every knowledge doc → its H2/H3 sections. **Grep a keyword here** "
        "to get the exact `path#anchor` to load, instead of reading a whole file. Each doc line "
        "carries its frontmatter tags, so keyword hits land on the section heading *or* the doc tags.\n\n"
        "Regenerate after editing docs: `python scripts/build_section_index.py` "
        "(parallel to `build_registry.py`).\n"
    )
    out = [head]
    for rel, label, headings in entries:
        out.append(f"\n## `{rel}` · {label}")
        for h, a in headings:
            out.append(f"- [{h}]({rel}#{a})")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    entries = collect()
    text = render(entries)
    sections = sum(len(h) for _, _, h in entries)
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        # ignore the auto-bumped date line when comparing for staleness
        norm = lambda t: re.sub(r"^updated: .*$", "updated: X", t, flags=re.M).strip()
        if norm(current) != norm(text):
            print("section-index.md is stale — run: python scripts/build_section_index.py")
            return 1
        print(f"section-index.md up to date ({len(entries)} docs, {sections} sections)")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(entries)} docs, {sections} sections)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
